# FeedMe Application Configuration
# Configuration for McDonald's online ordering system

# Common Configuration (shared across all environments)
common:
  deploymentrepo: "feedme"
  terraform_profile: "terraform"
  repo: "feedme"
  
  # AWS Configuration
  aws_region: "ap-southeast-1"
  
  # Common Application Settings
  app_name: "feedme"
  environment_prefix: "feedme"
  
  # Common Tags
  default_tags:
    Project: "FeedMe"
    Environment: "dev"
    Application: "McDonald-Ordering-System"
    ManagedBy: "Terraform"

# Environment-specific Configurations
environments:
  # Development Environment Configuration
  dev:
    deploymentname: "feedme-dev"
    costcenter: "Engineering-Dev"
    environment: "dev"
    
    # Network Configuration
    vpc_cidr: "10.1.0.0/16"
    availability_zones: 
      - "ap-southeast-1a"
      - "ap-southeast-1b"
    
    public_subnets:
      - "10.1.1.0/24"
      - "10.1.2.0/24"
    
    private_subnets:
      - "10.1.3.0/24"
      - "10.1.4.0/24"
    
    # ECS Configuration - Simple for dev
    ecs:
      cluster_name: "feedme-dev-cluster"
      service_name: "feedme-dev-backend"
      task_family: "feedme-dev-backend"
      container_name: "feedme-dev-backend"
      container_port: 3000
      cpu: 256
      memory: 512
      desired_count: 2
      # No auto-scaling for dev but ensure stability for demo
      enable_autoscaling: false
      # Demo stability settings
      deployment_minimum_healthy_percent: 50  # Allow more flexible deployments
      deployment_maximum_percent: 200
      # Container image version
      image_tag: "1.0"
    
    # Database Configuration - Minimal for dev
    database:
      cluster_identifier: "feedme-dev-docdb"
      instance_class: "db.t4g.medium"
      instance_count: 1
      port: 27017
      database_name: "DevOpsAssignment"
      backup_retention_period: 1
      backup_window: "07:00-09:00"
      skip_final_snapshot: true
    
    # Frontend Configuration
    frontend:
      bucket_suffix: "dev"
      cloudfront_enabled: false  # Use S3 directly for dev
    
    # Load Balancer Configuration
    load_balancer:
      name: "feedme-dev-alb"
      target_group_name: "feedme-dev-tg"
      health_check_path: "/orders"
    
    # Monitoring Configuration
    monitoring:
      enabled: true
      log_retention_days: 7
      enable_auto_recovery: true  # For auto-scaling only